import type { Metadata } from "next";
import {Roboto} from "next/font/google"
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/footer";


const roboto = Roboto({
  weight: ['400', '500', '700'],  
  subsets: ['latin'],  // Include the desired character subsets
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${roboto.className}`}
      ><Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
